# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Research Areas"
  url = "/researchareas"
  weight = 10





[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 50

[[main]]
  name = "People"
  url = "authors/"
  weight = 60

[[main]]
  name = "Conferences / Events"
  url = "talk/"
  weight = 70

  [[main]]
  name = "Blog"
  url = "/post"
  weight = 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
